//
// CentredRectangleF.cs
//

using Clf.LogicSystem.Common.ExtensionMethods;

namespace Clf.LogicSystem.Common.GeomertyPrimitives
{

  //
  // System.Drawing.RectangleF has its reference point (x,y) at the top left.
  //
  // In many situations it's more convenient to define a rectangle
  // in terms of its Centre Point and Size. This is the convention used 
  // in 'plain' files generated by GraphViz.
  //
  // This class provides derived properties for the TopLeft point etc
  // which are handy when the rectangle is being rendered as a visual.
  //

  public record CentredRectangleF ( 
    System.Drawing.PointF CentrePoint, 
    System.Drawing.SizeF  Size 
  ) {

    public float Width => Size.Width ;

    public float Height => Size.Height ;

    public System.Drawing.PointF TopLeftPoint => new System.Drawing.PointF(
      CentrePoint.X - Size.Width  / 2,
      CentrePoint.Y - Size.Height / 2
    ) ;

    public System.Drawing.PointF BottomRightPoint => new System.Drawing.PointF(
      CentrePoint.X + Size.Width  / 2,
      CentrePoint.Y + Size.Height / 2
    ) ;

    public System.Drawing.RectangleF ToSystemDrawingRectangleF ( ) 
    => new System.Drawing.RectangleF(
      x      : CentrePoint.X - 0.5f * Size.Width,
      y      : CentrePoint.Y - 0.5f * Size.Height,
      width  : Size.Width,
      height : Size.Height
    ) ;

    public CentredRectangleF ExpandedAllRoundBy ( System.Drawing.SizeF delta ) 
    => this with {
      Size = (
        Size 
      + delta // left and top
      + delta // right and bottom
      )
    } ;

    public CentredRectangleF ShrunkAllRoundBy ( System.Drawing.SizeF delta ) 
    => this with {
      Size = (
        Size 
      - delta // left and top
      - delta // right and bottom
      )
    } ;

    public CentredRectangleF ShrunkAllRoundBy ( float delta ) 
    => this.ShrunkAllRoundBy(
      new System.Drawing.SizeF(
        width  : delta, // left + right
        height : delta  // top + bottom
      )
    ) ;

    public static CentredRectangleF FromTopLeftPointAndSize (
      System.Drawing.Point topLeftPoint,
      System.Drawing.SizeF size
    ) {
      return FromSystemDrawingRectangleF(
        new System.Drawing.RectangleF(
          topLeftPoint,
          size
        )
      ) ;
    }

    public static CentredRectangleF FromSystemDrawingRectangleF ( System.Drawing.RectangleF rectangle ) 
    => new CentredRectangleF(
      rectangle.CentrePoint(),
      rectangle.Size
    ) ;

    public static System.Drawing.RectangleF ToSystemDrawingRectangleF ( System.Drawing.RectangleF rectangle ) 
    => new System.Drawing.RectangleF(
      rectangle.TopLeftPoint(),
      rectangle.Size
    ) ;

  }

}

